require 'erb'

task :clean do
  mkdir_p "target"
  rm_rf "target/*"
end

desc "Builds filters & dashboards"
task :build => :clean do
  puts "===> Building ..."
  compile_erb 'src/logstash-filters/default.conf.erb', 'target/logstash-filters-default.conf'
  create_bosh_job_template 'target/logstash-filters-default.conf', 'target/logstash-filters-default.conf.erb'

  puts "===> Artifacts:"
  puts `tree target`
end

desc "Runs unit tests against filters & dashboards"
task :test, [:rspec_files] => :build do |t, args|
  args.with_defaults(:rspec_files => "$(find test -name *spec.rb)")
  puts "===> Testing ..."
  sh %Q[ vendor/logstash/bin/rspec #{args[:rspec_files]} --color --format documentation ]
end

def compile_erb(source_file, dest_file)
  if File.extname(source_file) == '.erb'
    output = ERB.new(File.read(source_file)).result(binding)
    File.write(dest_file, output)
  else
    cp source_file, dest_file
  end
end

def create_bosh_job_template(source_file, dest_file)
  text = File.read(source_file)
  new_contents = text.gsub(/<%/, "<%%")
  File.open(dest_file, "w") {|file| file.puts new_contents }
end
