#!/bin/bash

set -e
set -u

mkdir tmp/test-$$

mkdir -p tmp/test-$$/repo/ci/tasks
cp -rp ci/tasks/test-logsearch-shipper-filters tmp/test-$$/repo/ci/tasks/test-logsearch-shipper-filters

mkdir -p tmp/test-$$/repo/src
cp -rp src/logstash-filters tmp/test-$$/repo/src/logstash-filters

fly \
  --target "${FLY_TARGET}" \
  execute \
  --config ci/tasks/logsearch-shipper-filters-test/task.yml \
  --input repo=./tmp/test-$$/repo \

EXIT=$?

rm -fr /tmp/test-$$

exit $EXIT
