---
name: logsearch
director_uuid: 3606f4d1-c2f8-48bc-913d-b5a4012e81ec

releases:
- name: logsearch
  version: latest

compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  serial: true
  canaries: 1
  canary_watch_time: 30000-120000
  update_watch_time: 30000-120000
  max_in_flight: 1
  max_errors: 1

resource_pools:
- name: warden
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties: {}

jobs:
- name: elasticsearch_master
  instances: 0
  release: logsearch
  templates:
  - name: elasticsearch
    release: logsearch
  - name: api
    release: logsearch
  - name: kibana
    release: logsearch
  update:
    serial: true
  resource_pool: warden
  networks:
  - name: default
    static_ips:
  properties:
    elasticsearch:
      node:
        allow_data: false

- name: haproxy
  instances: 0
  release: logsearch
  templates:
  - { name: haproxy, release: logsearch }
  resource_pool: warden
  networks:
  - name: default
  properties:
    haproxy:
      syslog_ingestor:
        port: 5514
      backend_servers: [10.244.2.6]
      backend_port: 5514


- name: elasticsearch_data
  release: logsearch
  templates:
  - name: elasticsearch
    release: logsearch
  update:
    serial: true
  instances: 0
  resource_pool: warden
  networks:
  - name: default
    static_ips:
  persistent_disk: 1024
  properties:
    elasticsearch:
      node:
        allow_master: false

- name: ingestor
  release: logsearch
  templates:
  - name: ingestor_syslog
    release: logsearch
  - name: ingestor_relp
    release: logsearch
  instances: 0
  resource_pool: warden
  networks:
  - name: default
    static_ips:

- name: cluster_monitor
  release: logsearch
  instances: 1
  templates:
    - { release: logsearch, name: queue }
    - { release: logsearch, name: parser }
    - { release: logsearch, name: ingestor_syslog }
    - { release: logsearch, name: elasticsearch }
    - { release: logsearch, name: elasticsearch_config }
    - { release: logsearch, name: curator }
    - { release: logsearch, name: kibana }
    - { release: logsearch, name: nats_to_syslog }
  resource_pool: warden
  networks:
  - name: default
    default:
    - dns
    - gateway
  persistent_disk: 0
  properties:
    kibana:
      elasticsearch: 127.0.0.1:9200
      port: 5601
    elasticsearch:
      master_hosts: [127.0.0.1]
      cluster_name: monitor
      allow_master: true
      allow_data: true
      #plugins:
      #- kopf: file:///var/vcap/packages/elasticsearch-plugins/elasticsearch-kopf.zip
    redis:
      host: 127.0.0.1
    curator:
      elasticsearch_host: 127.0.0.1
      elasticsearch_port: 9200
      purge_logs:
        retention_period: 7
    elasticsearch_config:
      elasticsearch:
        host: 127.0.0.1
        port: 9200
      bulk_data_files: []
      #templates:
        #- elk-for-pcf-monitor: ""
    #logstash_parser:
      #filters: ""
    nats_to_syslog:
      nats:
        subject: ">"
        user: nats
        password: nats-password
        port: 4222
        machines: [10.254.50.4]
      debug: true
      syslog:
        host: 127.0.0.1
        port: 514
    logstash_ingestor:
      syslog:
        port: 514


- name: queue
  release: logsearch
  templates:
  - name: queue
    release: logsearch
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.10

- name: parser
  release: logsearch
  templates:
  - name: parser
    release: logsearch
  instances: 0
  resource_pool: warden
  networks:
  - name: default
    default:
    - dns
    - gateway

- name: maintenance
  release: logsearch
  instances: 0
  templates:
  - name: elasticsearch_config
    release: logsearch
  - name: curator
    release: logsearch
  resource_pool: warden
  networks:
  - name: default
    default:
    - dns
    - gateway
  persistent_disk: 0

- name: test_e2e_errand
  lifecycle: errand
  release: logsearch
  templates:
  - name: test_e2e_errand
    release: logsearch
  instances: 1
  resource_pool: warden
  networks:
  - name: default
  properties:
    test_e2e_errand:
      syslog_host: "10.244.2.14"
      syslog_port: 5514
      elasticsearch_hostport: "10.244.2.2:9200"

# upload your backfill data
# $ sshpass -pc1oudc0w scp -i "$HOME/.ssh/vagrant" 2014102721.20141027220003-api-0.log.xz vcap@10.244.2.26:/tmp/backfill.xz
# restart ingestion of it all
# $ sshpass -pc1oudc0w ssh -i "$HOME/.ssh/vagrant" vcap@10.244.2.26 "echo c1oudc0w | sudo -p '' -S /var/vcap/jobs/ingestor_archiver/bin/reload /tmp/backfill.xz"
# utility if you want to block until complete
# $ sshpass -pc1oudc0w ssh -i "$HOME/.ssh/vagrant" vcap@10.244.2.26 "echo c1oudc0w | sudo -p '' -S /var/vcap/jobs/ingestor_archiver/bin/wait-until-loaded"
#- name: restorer
#  release: logsearch
#  templates:
#  - name: ingestor_archiver
#  - name: parser
#  instances: 1
#  resource_pool: warden
#  networks:
#  - name: default
#    default:
#    - dns
#    - gateway
#  properties:
#    redis:
#      key: "logstash-restorer"

properties:
  api:
    port: 80
  kibana:
    elasticsearch: 10.244.2.2:9200
    port: 5601
  curator:
    elasticsearch_host: 10.244.2.2
    purge_logs:
      retention_period: 3
  elasticsearch:
    master_hosts: [10.244.2.2]
    cluster_name: logsearch--bosh-lite
    drain: true
    exec:
      environment:
        ES_HEAP_SIZE: 256M
  redis:
    host: 10.244.2.10
  elasticsearch_config:
    elasticsearch:
      host: 10.244.2.2
      port: 9200
  logstash_parser:
    debug: true
    filters: |
             <% filtersconf = File.join(File.dirname(File.expand_path(__FILE__)), 'examples/filters.conf') %>
             <%= File.read(filtersconf).gsub(/^/, '             ').strip if File.exists? filtersconf %>
             # src/sample-logs/repo-commits/logstash-filters.conf
             <%= File.read("#{File.dirname(File.expand_path(__FILE__))}/src/sample-logs/repo-commits/logstash-filters.conf").gsub(/^/, '             ').strip %>
  logstash_ingestor:
    debug: true
    relp:
      port: 5515
    syslog:
      port: 5514
    syslog_tls:
      port: 443
      # ingestor-20241214a
      ssl_cert: |
          -----BEGIN CERTIFICATE-----
          MIICWjCCAcOgAwIBAgIJAN57Q1O2B6k0MA0GCSqGSIb3DQEBBQUAMG0xFTATBgNV
          BAoMDGxvZ3NlYXJjaC5pbzEeMBwGA1UECwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5
          MREwDwYDVQQDDAhpbmdlc3RvcjEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1w
          bGUuY29tMB4XDTE0MTIxNzIyMDkyNloXDTI0MTIxNDIyMDkyNlowXDEVMBMGA1UE
          CgwMbG9nc2VhcmNoLmlvMQ0wCwYDVQQLDARURVNUMREwDwYDVQQDDAhpbmdlc3Rv
          cjEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1wbGUuY29tMIGfMA0GCSqGSIb3
          DQEBAQUAA4GNADCBiQKBgQClKtJSXPwsPWPIhSFqPDcyQwvsIY/nF+vNjetX1xjC
          ATC6F6ZaKCcddF1JaomTiPR9+qVeNedGwvtcrCLyOYpqBWs6KuCq4dE/7QxEwova
          yLEQRGMvZW8OClpjY0PdrpX+ekqllD/7CTMYvabc3Kq0Q6WPZAGLo01YoW2KKr13
          GQIDAQABoxMwETAPBgNVHREECDAGhwQK9AIOMA0GCSqGSIb3DQEBBQUAA4GBAFLV
          Z59nPFO1+W407lDCm4tXV3RpUCt4drAqNp1xum6U9fkcgzU0ZhrfmVCqGdFGWxxM
          Jhe1iAbho/Jb85V9hB9txr2Uh5Xvr0r0faeJYqFF+NCc9G+PKiNVwbId0rH2bfwr
          YLxYAgzDDozZ1bUSUQKbkiX8jSQHB63MPZXSAMWb
          -----END CERTIFICATE-----
      ssl_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIICXAIBAAKBgQClKtJSXPwsPWPIhSFqPDcyQwvsIY/nF+vNjetX1xjCATC6F6Za
          KCcddF1JaomTiPR9+qVeNedGwvtcrCLyOYpqBWs6KuCq4dE/7QxEwovayLEQRGMv
          ZW8OClpjY0PdrpX+ekqllD/7CTMYvabc3Kq0Q6WPZAGLo01YoW2KKr13GQIDAQAB
          AoGAHX57Flgic+f2hJ05bVYZaTFN1Lndj5/W7Nr19rajZil+QQzuGNVovrrD2dNb
          g+wF9OUoWJ15kkpJRrA6gVTDIYgZwoWjpo1X6NKfiMGbtITSePfwB17egeaVvoKW
          nxfhd5absxOAC13hXNGEIyklzBMzyikTbrlemeo07gLq+H0CQQDWzxVTIXesjQ2S
          Um9vvsUdlxqU5AjvsVPDZP3/d3NYF0ZALyyeqg1mE+pc4gEXw3T5Q5IMyxxFZjqQ
          m2mpuZzDAkEAxNbXko2mSopYZ5/LR6KJFvze8t70b0TUvlvPvM3M6pMeViqSrfyt
          QvHMNPRxbgoniNwm7W9x6Jp2UAUzH2kO8wJBAJc3KkTeH3fpx+8EdwwMGIkPERhV
          OvE5PMUlOCT5usn9gGe4jcmX3lzIkkgWlTxcTOEYLx0wclNsdrfLn+NqFa8CQByU
          xYB2KOsx41xIi4+/PgCkfwrs7LkrWWi6lBNqHpMBAaqpS9sPkWjjCy+1PrMnrk3l
          CZH4WKXZp8w+tQmei5kCQCxQ6Se1d1fSYQlLsCoTKmbcOjFoT5joj1nMIwSwn/Sy
          eevXlJLkedUMlEntH3b+dQjaRSWwWWtjzxY/Ou0CLKI=
          -----END RSA PRIVATE KEY-----


# Warden CPI requires crappy network settings; so "hide" them away here
networks:
- name: default
  # Assumes up to 7 VMs, including 4 static and 3 dynamic.
  # Plus 7 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2
  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static:
    - 10.244.2.6
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static:
    - 10.244.2.10
  - cloud_properties:
      name: random
    range: 10.244.2.12/30
    reserved:
    - 10.244.2.13
    static:
    - 10.244.2.14

  - cloud_properties:
      name: random
    range: 10.244.2.16/30
    reserved:
    - 10.244.2.17
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.20/30
    reserved:
    - 10.244.2.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.24/30
    reserved:
    - 10.244.2.25
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.2.28/30
    reserved:
    - 10.244.2.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.32/30
    reserved:
    - 10.244.2.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.36/30
    reserved:
    - 10.244.2.37
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.40/30
    reserved:
    - 10.244.2.41
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.44/30
    reserved:
    - 10.244.2.45
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.48/30
    reserved:
    - 10.244.2.49
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.52/30
    reserved:
    - 10.244.2.53
    static: []

apply_spec:
  properties:
    ntp:
      - 0.europe.pool.ntp.org
      - 1.europe.pool.ntp.org
      - 2.europe.pool.ntp.org
      - 3.europe.pool.ntp.org
