---
meta:
  environment: (( merge ))

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-600000
  update_watch_time: 1000-600000
  serial: false

properties:
  elasticsearch:
    exec:
      environment:
        ES_HEAP_SIZE: 500000K

jobs:
  - name: api
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(0) ))

  - name: ingestor
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(1) ))

  - name: queue
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(2) ))

  - name: log_parser
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(3) ))

  - name: elasticsearch_persistent
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(4) ))

  - name: elasticsearch_autoscale
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(5) ))

compilation:
  cloud_properties:
    name: random

resource_pools:
- name: logsearch
  cloud_properties:
    name: random

- name: logsearch_api
  cloud_properties:
    name: random

- name: logsearch_ingestor
  cloud_properties:
    name: random

- name: logsearch_elasticsearch
  cloud_properties:
    name: random

networks: (( merge || networks_default ))
networks_default:
- name: default
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.0.0/30
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2
  - cloud_properties:
      name: random
    range: 10.244.0.4/30
    reserved:
    - 10.244.0.5
    static:
    - 10.244.0.6
  - cloud_properties:
      name: random
    range: 10.244.0.8/30
    reserved:
    - 10.244.0.9
    static:
    - 10.244.0.10
  - cloud_properties:
      name: random
    range: 10.244.0.12/30
    reserved:
    - 10.244.0.13
    static:
    - 10.244.0.14
  - cloud_properties:
      name: random
    range: 10.244.0.16/30
    reserved:
    - 10.244.0.17
    static:
    - 10.244.0.18
  - cloud_properties:
      name: random
    range: 10.244.0.20/30
    reserved:
    - 10.244.0.21
    static:
    - 10.244.0.22
  - cloud_properties:
      name: random
    range: 10.244.0.24/30
    reserved:
    - 10.244.0.25
    static:
    - 10.244.0.26
  - cloud_properties:
      name: random
    range: 10.244.0.28/30
    reserved:
    - 10.244.0.29
    static:
    - 10.244.0.30
  - cloud_properties:
      name: random
    range: 10.244.0.32/30
    reserved:
    - 10.244.0.33
    static:
    - 10.244.0.34
  - cloud_properties:
      name: random
    range: 10.244.0.36/30
    reserved:
    - 10.244.0.37
    static:
    - 10.244.0.38
  - cloud_properties:
      name: random
    range: 10.244.0.40/30
    reserved:
    - 10.244.0.41
    static:
    - 10.244.0.42
  - cloud_properties:
      name: random
    range: 10.244.0.44/30
    reserved:
    - 10.244.0.45
    static:
    - 10.244.0.46
  - cloud_properties:
      name: random
    range: 10.244.0.48/30
    reserved:
    - 10.244.0.49
    static:
    - 10.244.0.50
  - cloud_properties:
      name: random
    range: 10.244.0.52/30
    reserved:
    - 10.244.0.53
    static:
    - 10.244.0.54
  - cloud_properties:
      name: random
    range: 10.244.0.56/30
    reserved:
    - 10.244.0.57
    static:
    - 10.244.0.58
  - cloud_properties:
      name: random
    range: 10.244.0.60/30
    reserved:
    - 10.244.0.61
    static:
    - 10.244.0.62
  - cloud_properties:
      name: random
    range: 10.244.0.64/30
    reserved:
    - 10.244.0.65
    static:
    - 10.244.0.66
  - cloud_properties:
      name: random
    range: 10.244.0.68/30
    reserved:
    - 10.244.0.69
    static:
    - 10.244.0.70
  - cloud_properties:
      name: random
    range: 10.244.0.72/30
    reserved:
    - 10.244.0.73
    static:
    - 10.244.0.74
  - cloud_properties:
      name: random
    range: 10.244.0.76/30
    reserved:
    - 10.244.0.77
    static:
    - 10.244.0.78
  - cloud_properties:
      name: random
    range: 10.244.0.80/30
    reserved:
    - 10.244.0.81
    static:
    - 10.244.0.82
  - cloud_properties:
      name: random
    range: 10.244.0.84/30
    reserved:
    - 10.244.0.85
    static:
    - 10.244.0.86
  - cloud_properties:
      name: random
    range: 10.244.0.88/30
    reserved:
    - 10.244.0.89
    static:
    - 10.244.0.90
  - cloud_properties:
      name: random
    range: 10.244.0.92/30
    reserved:
    - 10.244.0.93
    static:
    - 10.244.0.94
  - cloud_properties:
      name: random
    range: 10.244.0.96/30
    reserved:
    - 10.244.0.97
    static:
    - 10.244.0.98
  - cloud_properties:
      name: random
    range: 10.244.0.100/30
    reserved:
    - 10.244.0.101
    static:
    - 10.244.0.102
  - cloud_properties:
      name: random
    range: 10.244.0.104/30
    reserved:
    - 10.244.0.105
    static:
    - 10.244.0.106
  - cloud_properties:
      name: random
    range: 10.244.0.108/30
    reserved:
    - 10.244.0.109
    static:
    - 10.244.0.110
  - cloud_properties:
      name: random
    range: 10.244.0.112/30
    reserved:
    - 10.244.0.113
    static:
    - 10.244.0.114
  - cloud_properties:
      name: random
    range: 10.244.0.116/30
    reserved:
    - 10.244.0.117
    static:
    - 10.244.0.118
  - cloud_properties:
      name: random
    range: 10.244.0.120/30
    reserved:
    - 10.244.0.121
    static:
    - 10.244.0.122
  - cloud_properties:
      name: random
    range: 10.244.0.124/30
    reserved:
    - 10.244.0.125
    static:
    - 10.244.0.126
  - cloud_properties:
      name: random
    range: 10.244.0.128/30
    reserved:
    - 10.244.0.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.132/30
    reserved:
    - 10.244.0.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.136/30
    reserved:
    - 10.244.0.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.140/30
    reserved:
    - 10.244.0.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.144/30
    reserved:
    - 10.244.0.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.148/30
    reserved:
    - 10.244.0.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.152/30
    reserved:
    - 10.244.0.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.156/30
    reserved:
    - 10.244.0.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.160/30
    reserved:
    - 10.244.0.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.164/30
    reserved:
    - 10.244.0.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.168/30
    reserved:
    - 10.244.0.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.172/30
    reserved:
    - 10.244.0.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.176/30
    reserved:
    - 10.244.0.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.180/30
    reserved:
    - 10.244.0.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.184/30
    reserved:
    - 10.244.0.185
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.188/30
    reserved:
    - 10.244.0.189
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.192/30
    reserved:
    - 10.244.0.193
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.196/30
    reserved:
    - 10.244.0.197
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.200/30
    reserved:
    - 10.244.0.201
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.204/30
    reserved:
    - 10.244.0.205
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.208/30
    reserved:
    - 10.244.0.209
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.212/30
    reserved:
    - 10.244.0.213
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.216/30
    reserved:
    - 10.244.0.217
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.220/30
    reserved:
    - 10.244.0.221
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.224/30
    reserved:
    - 10.244.0.225
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.228/30
    reserved:
    - 10.244.0.229
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.232/30
    reserved:
    - 10.244.0.233
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.236/30
    reserved:
    - 10.244.0.237
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.240/30
    reserved:
    - 10.244.0.241
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.244/30
    reserved:
    - 10.244.0.245
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.248/30
    reserved:
    - 10.244.0.249
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.252/30
    reserved:
    - 10.244.0.253
    static: []
