---
meta:
  <<: (( merge ))
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  availability_zone: (( merge ))

jobs:
  - name: api
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(0) ))

  - name: ingestor
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(1) ))

  - name: queue
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(2) ))

  - name: parser
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(5) ))

  - name: elasticsearch_persistent
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(3) ))

  - name: elasticsearch_autoscale
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(4) ))

compilation:
  cloud_properties:
    instance_type: c4.large

resource_pools:
  - name: logsearch_api
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "t2.micro" ))
      elbs: ~

  - name: logsearch_ingestor
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "t2.micro" ))
      elbs: ~

  - name: logsearch_elasticsearch
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "t2.small" ))
      elbs: ~

  - name: logsearch_queue
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "t2.micro" ))
      elbs: ~

  - name: logsearch_parser
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "t2.micro" ))
      elbs: ~

  - name: logsearch_curator
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "t2.micro" ))
      elbs: ~

networks: (( merge ))
