#!/bin/sh

spruce="$(dirname "$0")/../bin/spruce-$(uname -s)"

templates=$(dirname "$0")/../templates

infrastructure=$1

shift

if [ "$infrastructure" != "aws" ] && \
    [ "$infrastructure" != "gcp" ] && \
    [ "$infrastructure" != "openstack" ] && \
    [ "$infrastructure" != "warden" ] && \
    [ "$infrastructure" != "vsphere" ] ; then
  echo "usage: ./generate_deployment_manifest <aws|gcp|openstack|warden|vsphere> [stubs...]" 1>&2
  exit 1
fi

$spruce merge --prune meta \
  "$templates/logsearch-deployment.yml" \
  "$templates/logsearch-jobs.yml" \
  "$templates/logsearch-infrastructure-${infrastructure}.yml" \
  "$@"
