#!/bin/sh

templates=$(dirname $0)/../templates

infrastructure=$1

shift

if [ "$infrastructure" != "aws" ] && \
    [ "$infrastructure" != "warden" ] && \
    [ "$infrastructure" != "vsphere" ] ; then
  echo "usage: ./generate_deployment_manifest <aws|warden|vsphere> [stubs...]"
  exit 1
fi

spiff merge \
  $templates/logsearch-deployment.yml \
  $templates/logsearch-jobs.yml \
  $templates/logsearch-infrastructure-${infrastructure}.yml \
  "$@"
