require 'erb'

task :clean do
  mkdir_p "target"
  rm_rf "target/*"
end

desc "Builds filters & dashboards"
task :build => :clean do
  puts "===> Building ..."

  compile_erb 'src/logstash-filters/syslog_standard.conf.erb', 'target/logstash-filters-syslog-standard.conf'
  compile_erb 'src/logstash-filters/haproxy.conf.erb', 'target/logstash-filters-haproxy.conf'

  ENV["DICTIONARY_FILE"] = "./src/logstash-filters/snippets/default_deployment_dictionary.conf"
  compile_erb 'src/logstash-filters/bosh_nats.conf.erb', 'target/logstash-filters-bosh-nats.conf'

  ENV["DICTIONARY_FILE"] = "./src/logstash-filters/snippets/monitor_deployment_dictionary.conf"
  compile_erb 'src/logstash-filters/bosh_nats.conf.erb', 'target/logstash-filters-bosh-nats-monitor.conf'

  compile_erb 'src/logstash-filters/metric.conf.erb', 'target/logstash-filters-metric.conf'

  puts "===> Artifacts:"
  puts `find target`
end

desc "Runs unit tests against filters & dashboards"
task :test, [:rspec_files] => :build do |t, args|
  args.with_defaults(:rspec_files => "$(find test -name '*spec.rb')")
  puts "===> Testing ..."
  sh %Q[ LANGUAGE="C.UTF-8" LC_ALL="C.UTF-8" LANG="C.UTF-8" vendor/logstash/bin/rspec #{args[:rspec_files]} --colour --format progress --format html --out target/parsing_rules.html]
end

def compile_erb(source_file, dest_file)
  if File.extname(source_file) == '.erb'
    output = ERB.new(File.read(source_file)).result(binding)
    File.write(dest_file, output)
  else
    cp source_file, dest_file
  end
end
